# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Rigoblock
email: gab@rigoblock.com
description: RigoBlock is a blockchain protocol for decentralized asset management. A complete solution to develop applications for asset management (i.e. for the fund management industry). The RigoBlock protocol offers new types of incentives for managers and investors by aligning their interests through the Proof-of-Performance algorithm, by eliminating management fees and performance fees from the funds.
short_description: Decentralized Asset Management
baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://rigoblock.com" # the base hostname & protocol for your site, e.g. http://example.com
url: "http://localhost:4000"
twitter_username: rigoblock
github_username: rigoblock
facebook_username: RigoBlockProtocol
linkedin_username: company/rigoblock
discord_username: channels/rigoblock
telegram_link: https://t.me/rigoblockprotocol
beta_portal_link: https://beta.rigoblock.com

token_sale_popup: true

mailchimp_list: //rigoblock.us15.list-manage.com/subscribe/post?u=61d62dbd39a3052da7ec9fdfa&amp;id=37290603c2


keywords: [asset management,decentralized asset management,decentralized hedge fund,investment management,blockchain investment management,blockchain asset management,decentralized fund infrastructure,token pool,token pools,ethereum mining,proof of stake mining,proof of stake,decentralized exchange,proof of performance,mutual funds,online share trading,managed funds,alternative investments,day trading strategies,top hedge funds,asset manager,ethereum asset manager,blockchain fund,hedge fund company,hedge fund manager]

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-inline-svg
  - jekyll-sitemap
  - jekyll-autoprefixer
collections:
  - project
  - press
  - positions
assets:
  sources:
    - assets/css
    - assets/fonts
    - assets/images
    - assets/videos
    - assets/javascript
    - assets/video
    - assets/image
    - assets/img
    - assets/js
    - assets/downloads
    - assets/pdf
    - assets/favicons
    - _assets/css
    - _assets/fonts
    - _assets/images
    - _assets/videos
    - _assets/javascript
    - _assets/video
    - _assets/image
    - _assets/img
    - _assets/js
    - _assets/downloads
    - _assets/pdf
    - _assets/favicons
svg:
  optimize: true
autoprefixer:
  browsers:
    - last 15 versions

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
